# Generated by Django 4.2.1 on 2023-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('pending', 'pending'), ('doing', 'doing'), ('done', 'done')], max_length=7),
        ),
    ]
