# Generated by Django 4.2.1 on 2023-06-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'doing'), ('done', 'done')], max_length=5),
        ),
    ]
